### PR TITLE
SLING-11590 Make compatible with m2e 2.x

### PR DESCRIPTION
**Pull request by kwin**
Require at least Eclipse 2022-09
Update Eclipse plugins to Java 17
Update to Tycho 2.7.5
No longer generate p2 repo for plain OSGi bundles
Update to latest dependencies/parent poms

### CODE REVIEW

**Comment by rombert** [comment]
@kwin - FWIW I am following this PR, not actively commenting since it seems to still be under development. I have no issues to raise - on the contrary, really happy that you are taking this up.

Let me know when you think this is stable and I'd be happy to make a high-level review.

**Comment by kwin** [comment]
@rombert Any idea why the ITs fail?

**Comment by rombert** [comment]
@kwin - one test might be related to your work 

```org.apache.sling.ide.eclipse.m2e.internal.LegacyMavenBundleProjectTest.testLegacyMavenBundleProjectHasErrorMarker  Time elapsed: 60.193 s  <<< ERROR!

java.lang.RuntimeException: Did not find error message starting with 'Missing m2e incremental support'
```

The other one I am really not sure about

```
org.apache.sling.ide.eclipse.m2e.internal.MavenProjectUtilsTest.inferDefaultProvisioningModelDirectories  Time elapsed: 61.547 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: <src/main/provisioning>
     but: was null
```

**Comment by kwin** [comment]
@rombert Can you try locally. For me the tests locally always succeed with 
```
Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec
Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.1", arch: "aarch64", family: "mac"
```

**Comment by kwin** [comment]
@rombert The ITs are still intermittently unstable on Jenkins (but not worse than in master), therefore I would like to merge and rather do subsequent fixes separately. Locally they work well for me.

**Comment by rombert** [comment]
@kwin - all tests ( shared/cli/eclipse) pass locally for me as well, with

```
Apache Maven 3.8.6 (SUSE 3.8.6-2.1)
Maven home: /usr/share/maven
Java version: 17.0.5, vendor: N/A, runtime: /usr/lib64/jvm/java-17-openjdk-17
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.0.3-1-default", arch: "amd64", family: "unix"
```

I'm in favour of merging and stabilising CI afterwards.

**Pull request merged**
