### PR TITLE
SLING-9117 improve guessing of jcr_root

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by rombert** [comment]
@kwin - not sure what to make of the CI errors. I will be away for the next two weeks so if you think they are unrelated please merge.

**Comment by kwin** [comment]
I don't think it is related
> ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project org.apache.sling.ide.cli: Compilation failure: Compilation failure:
[ERROR] error reading F:\hudson\m2_repository\org\apache\sling\ide\org.apache.sling.ide.api\1.2.3-SNAPSHOT\org.apache.sling.ide.api-1.2.3-SNAPSHOT.jar; cannot read zip file
Rather looks like a transient transmission error!

**Comment by rombert** [comment]
@kwin - I've retriggered both builds, let's see what happens.

**Comment by rombert** [comment]
One check failed, another was aborted "Sending interrupt signal to process". I think we're good to go.

**Pull request merged**
